name: groq-chatbot
package: .

command:
  name: server
  args: []

web:
  routes:
    - path: /
      to: 8080

env:
  - GROQ_API_BASE=https://api.groq.com/openai/v1
secrets:
  - GROQ_API_KEY
  - UPSTASH_REDIS_REST_URL
  - UPSTASH_REDIS_REST_TOKEN

